// Generated by https://quicktype.io

export interface CatalogoEstadoCivil {
    result:              Result[];
    targetUrl:           null;
    success:             boolean;
    error:               null;
    unAuthorizedRequest: boolean;
    __abp:               boolean;
}

export interface Result {
    id:          number;
    nombre:      string;
    descripcion: string;
    index:       number;
    estaActivo:  boolean;
    tipo:        number;
}
